name: Deploy to AWS S#

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name : build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
#          args: --acl public-read --follow-symlinks --delete
##            --exclude '.git*/*'
#        env:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws-region: us-east-1

      - name: deploy code to s3
        run: |
          aws s3 sync
#          . s3://build2/